### ISSUE TITLE
provide "add" and "update"?

### ISSUE THREAD

**Issue by hannesm** [hannesm/gmap#1]
in lots of use cases (parsing protocols), I end up with the side condition "there may be at most one extension of each type present".  now, the standard `Map.add` replaces a potential existing value - same is done by `Gmap.add`.

It may be worth to explicitly provide `add : k -> v -> t -> t option` and `replace/update : k -> v -> t -> t`.  the issue left is naming -- `add` in OCaml is already used for the destructive update in `Hashtbl` and `Map`, using it for a different purpose will confuse people.  Any suggestions for a function name that does non-replacing addition to a map?

**Comment by cfcs** [comment]
1) I'm always confused by `add`'s destructive semantics. Maybe it could be changed from
```
> val Gmap.Make.add 'a key -> 'a -> t -> t                                      
    [add key value t] adds the binding [V (key, value)] to [t].
```
to something more explicit like
`[add key value t] adds the binding [V (key, value)] to [t], replacing any existing [key] binding.`
  Same for `addv` I guess.

2) FWIW I've also seen `reassign` used for `replace`/`update`. I like `replace`

3) I think a `mapv` function would be nice, something along the lines of `val mapv : 'a key -> ('a option -> 'a option) -> t -> t`

**Comment by hannesm** [comment]
@cfcs in f5ea59fc685e30133efd5fceb12dc4946f96712f I addressed your concerns and this issue.

(1) `add`, as defined in OCaml for collections (see [`Set`](http://caml.inria.fr/pub/docs/manual-ocaml/libref/Set.S.html#VALadd), [`Map`](http://caml.inria.fr/pub/docs/manual-ocaml/libref/Map.S.html#VALadd), [`Hashtbl`](http://caml.inria.fr/pub/docs/manual-ocaml/libref/Hashtbl.html#VALadd)) is destructive.  Yes, I improved the wording in the docs.

(2) since `add` is used for `destructive update` (see above), and `update` for "replace value x with y for key k" (see below), there's still need for a (better name for) ~~`add_unbound`~~ `add_unless_bound` -- which I just introduced.

(3) `update` is proposed in https://github.com/ocaml/ocaml/pull/1389 for `Hashtbl` which a very similar signature, `t -> 'a key -> ('a option -> 'a option)` -> unit` (and [`Map.update`](http://caml.inria.fr/pub/docs/manual-ocaml/libref/Map.S.html#VALupdate) is there since 4.06.0 with `'a key -> ('a option -> 'a option) -> t -> t`) - so far I haven't had a use case for this, but I can see value.

**Comment by cfcs** [comment]
Nice!
